export const GET_DATA="GET_DATA"
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const GET_DATA_FAIL="GET_DATA_FAIL"


export const GET_CITY="GET_CITY"
export const GET_CITY_SUCCESS="GET_CITY_SUCCESS"
export const GET_CITY_FAIL="GET_CITY_FAIL"